version: "3"

services:

  web:
    build: .
    # expose: 
    #   - 8000
    ports:
      - 80:80
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
  
volumes:
  static_volume:
  media_volume: