# Generated by Django 3.2.6 on 2021-11-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211124_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': 'Course Section', 'verbose_name_plural': 'Course Sections'},
        ),
        migrations.AlterModelOptions(
            name='programsection',
            options={'verbose_name': 'Program Section', 'verbose_name_plural': 'Program Sections'},
        ),
        migrations.AlterModelOptions(
            name='projectsection',
            options={'verbose_name': 'Project Section', 'verbose_name_plural': 'Project Sections'},
        ),
        migrations.AlterModelOptions(
            name='publicationsection',
            options={'verbose_name': 'Publication Section', 'verbose_name_plural': 'Publication Sections'},
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
