# Generated by Django 3.2.3 on 2021-06-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
