# Generated by Django 3.1.5 on 2021-02-01 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_researchpaper_webinar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('customsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.customsection')),
            ],
            bases=('home.customsection',),
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('customsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.customsection')),
            ],
            bases=('home.customsection',),
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('customsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.customsection')),
            ],
            bases=('home.customsection',),
        ),
        migrations.CreateModel(
            name='PublicationSection',
            fields=[
                ('customsection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.customsection')),
            ],
            bases=('home.customsection',),
        ),
    ]
