# Generated by Django 3.2.6 on 2021-11-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211125_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='date_published',
        ),
    ]
