# Generated by Django 3.2.6 on 2021-11-25 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blogpostpage_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
