# Generated by Django 3.2.3 on 2021-06-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_notifications_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
