# Generated by Django 3.1.5 on 2021-02-01 16:28

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_coursesection_customsection_programsection_projectsection_publicationsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sections',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.PublicationSection'),
        ),
    ]
