# Generated by Django 3.2.3 on 2021-06-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_notification_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
