# Generated by Django 3.2.6 on 2021-12-23 08:22

from django.db import migrations, models
import home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211125_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', home.models.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', home.models.ImageChooserBlock(icon='image')), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media'))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='topics')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', home.models.ImageChooserBlock(icon='image'))], blank=True, null=True),
        ),
    ]
