# Generated by Django 3.2.3 on 2021-06-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceissue',
            name='member',
        ),
        migrations.AddField(
            model_name='attendanceissue',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='absentee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendanceissue',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='attendanceissue',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
