# Generated by Django 3.2.8 on 2021-12-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211203_2158'),
        ('home', '0010_blogpostpage_is_pinned'),
    ]

    operations = [
    ]
