# Generated by Django 3.2.3 on 2021-06-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210606_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails')),
                ('youtube_link', models.TextField()),
                ('registration_form', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Symposium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='Symposium_thumbnails')),
                ('youtube_link', models.TextField()),
                ('registration_form', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='attendanceissue',
            options={'permissions': [('add_absentee', 'Ask Member reasons for leave.(Attendance System)'), ('mark_member_on_leave', 'Allow Leave for member (Attendance System)')]},
        ),
        migrations.AddField(
            model_name='absentee',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minute_file',
            field=models.FileField(default=False, upload_to='minute_file'),
            preserve_default=False,
        ),
    ]
