# Generated by Django 3.2.3 on 2021-06-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210613_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceissue',
            options={'permissions': [('manage_attendance', 'Can Manage Attendance System')]},
        ),
    ]
