# Generated by Django 3.2.8 on 2021-12-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211225_1205'),
        ('home', '0012_auto_20211225_1152'),
    ]

    operations = [
    ]
