# Generated by Django 3.2.3 on 2021-06-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_attendanceissue_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absentee',
            old_name='on_leave',
            new_name='is_filled',
        ),
    ]
