# Generated by Django 3.2.3 on 2021-06-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_on_leave_absentee_is_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
