# Generated by Django 3.2.6 on 2021-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_0011_auto_20211225_1205_0012_auto_20211225_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
