# Generated by Django 3.2.6 on 2021-12-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_webinar_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='date',
            new_name='program_date',
        ),
    ]
