# Generated by Django 3.2.3 on 2021-06-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210615_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='research_paper_file',
            field=models.FileField(null=True, upload_to='research_papers'),
        ),
    ]
