# Generated by Django 3.2.6 on 2021-12-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_date_webinar_program_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='slug',
            field=models.SlugField(default='smt', unique=True),
            preserve_default=False,
        ),
    ]
