# Generated by Django 3.2.3 on 2021-06-16 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_researchpaper_research_paper_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskToLeaveMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
