# Generated by Django 3.2.3 on 2021-06-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_asktoleavemembers_asktoleavemember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AskToLeaveMember',
            new_name='AskForLeaveMember',
        ),
    ]
