# Generated by Django 3.2.3 on 2021-07-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_asktoleavemember_askforleavemember'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('issue_date', 'member'), name='unique member and issue_date'),
        ),
    ]
