# Generated by Django 3.2.6 on 2022-01-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_researchpaper_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
