# Generated by Django 3.2.3 on 2021-08-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_attendance_unique member and issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceissue',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
