# Generated by Django 3.2.3 on 2021-08-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_user_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thumbnail',
        ),
    ]
