# Generated by Django 3.2.11 on 2022-01-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_user_priority_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='youtube_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='registration_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symposium',
            name='youtube_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='registration_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='youtube_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
