# Generated by Django 3.2.3 on 2021-08-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_user_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, default='Member', max_length=1000, null=True),
        ),
    ]
