# Generated by Django 3.2.6 on 2021-10-12 08:17

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_user_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='askforleavemember',
            options={'permissions': [('manage_attendance', 'Can Manage Attendance System')]},
        ),
        migrations.AddField(
            model_name='project',
            name='sections',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.ProjectSection'),
        ),
    ]
