# Generated by Django 3.2.11 on 2022-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20220118_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaperSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Research Paper Section',
                'verbose_name_plural': 'Research Paper Sections',
            },
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='sections',
            field=models.ManyToManyField(blank=True, null=True, to='home.ResearchPaperSection'),
        ),
    ]
