# Generated by Django 3.2.6 on 2021-10-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211012_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sections',
            field=models.ManyToManyField(blank=True, to='home.ProjectSection'),
        ),
    ]
