# Generated by Django 3.2.6 on 2021-10-18 04:14

from django.conf import settings
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_project_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='research_paper_file',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='topics')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='refrences',
            field=wagtail.core.fields.StreamField([('refrence', wagtail.core.blocks.CharBlock(form_classname='refrence'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='view',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='researchpaper',
            name='author',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
