# Generated by Django 3.2.8 on 2021-10-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20211018_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='projects', to='home.ProjectSection'),
        ),
    ]
