# Generated by Django 3.2.6 on 2021-10-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_highlight',
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='is_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='is_highlight',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
