# Generated by Django 3.2.8 on 2021-10-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_project_sections'),
        ('home', '0031_auto_20211025_1115'),
    ]

    operations = [
    ]
